language: node_js
matrix:
  include:
    - node_js: "8"
      env:
          - TARGET=test
          - TESTS=test/index test/readme test/index.4.x
    - node_js: "10"
      env:
          - TARGET=test
          - TESTS=test/index test/readme test/index.4.x
    - node_js: "12"
      env:
          - TARGET=test
          - TESTS=test/index test/readme test/index.4.x
install:
- npm install
- npm install -g codecov istanbul
script:
- npm run $TARGET
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --timeout 5s -R spec $TESTS
- codecov
