node_js:
- "0.12"
- "4"
- "6"
- "7"
language: node_js
install:
- npm install
- npm install -g codecov istanbul
script:
- npm test
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --timeout 3s -R spec
- codecov
